// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://phoehfjdfbygusbefasd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBob2VoZmpkZmJ5Z3VzYmVmYXNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0OTczNjAsImV4cCI6MjA2NjA3MzM2MH0.InHePa3zRmkn8tSq7BqHrXTpxJfGaO4a1Xgh9LdY58o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);